export const Click = 'click'
export const ContextMenu = 'contextmenu'
export const KeyDown = 'keydown'
export const KeyUp = 'keyup'
export const MouseDown = 'mousedown'
export const MouseEnter = 'mouseenter'
export const MouseUp = 'mouseup'
